// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeohAutorizador.Infrastructure.Context;

namespace NeohAutorizador.Infrastructure.Migrations
{
    [DbContext(typeof(NeohAutorizadorContext))]
    partial class NeohAutorizadorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NeohAutorizador.ApplicationCore.Entities.Exemplo", b =>
                {
                    b.Property<int>("ExemploId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_EXEMPLO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasMaxLength(200);

                    b.HasKey("ExemploId")
                        .HasName("ID_EXEMPLO");

                    b.ToTable("EXEMPLOS");
                });

            modelBuilder.Entity("NeohAutorizador.ApplicationCore.Entities.ExemploItem", b =>
                {
                    b.Property<int>("ExemploItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExemploId");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasMaxLength(200);

                    b.HasKey("ExemploItemId")
                        .HasName("ID");

                    b.HasIndex("ExemploId");

                    b.ToTable("EXEMPLOS_ITENS");
                });

            modelBuilder.Entity("NeohAutorizador.ApplicationCore.Entities.ExemploItem", b =>
                {
                    b.HasOne("NeohAutorizador.ApplicationCore.Entities.Exemplo", "Exemplo")
                        .WithMany("Itens")
                        .HasForeignKey("ExemploId");
                });
#pragma warning restore 612, 618
        }
    }
}
